package com.tservice.Model;
// Generated 29/06/2015 02:52:59 PM by Hibernate Tools 4.3.1



/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private int id;
     private Eventos eventos;
     private Noticias noticias;
     private Usuarios usuarios;
     private String tipo;
     private Integer calificacion;

    public Calificacion() {
    }

	
    public Calificacion(int id, Eventos eventos, Noticias noticias, Usuarios usuarios) {
        this.id = id;
        this.eventos = eventos;
        this.noticias = noticias;
        this.usuarios = usuarios;
    }
    public Calificacion(int id, Eventos eventos, Noticias noticias, Usuarios usuarios, String tipo, Integer calificacion) {
       this.id = id;
       this.eventos = eventos;
       this.noticias = noticias;
       this.usuarios = usuarios;
       this.tipo = tipo;
       this.calificacion = calificacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Eventos getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Eventos eventos) {
        this.eventos = eventos;
    }
    public Noticias getNoticias() {
        return this.noticias;
    }
    
    public void setNoticias(Noticias noticias) {
        this.noticias = noticias;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }




}


