package com.tservice.Model;
// Generated 14-jun-2015 22:57:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Carreras generated by hbm2java
 */
@Entity
@Table(name="carreras"
)
public class Carreras  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Usuarios> usuarioses = new HashSet(0);

    public Carreras() {
    }

    public Carreras(String nombre, Set<Usuarios> usuarioses) {
       this.nombre = nombre;
       this.usuarioses = usuarioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


@ManyToMany(fetch=FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinTable(name="carreras_has_usuarios", joinColumns = { 
        @JoinColumn(name="carreras_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="usuarios_carne", nullable=false, updatable=false) })
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }




}


