package com.tservice.Model;
// Generated 30-jun-2015 13:06:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Carreras generated by hbm2java
 */
@Entity
@Table(name="carreras")
public class Carreras  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descrpcion;
     private Set<Eventos> eventoses = new HashSet(0);
     private Set<Usuarios> usuarioses = new HashSet(0);
     private Set<Intereses> intereseses = new HashSet(0);

    public Carreras() {
    }

    public Carreras(String nombre, String descrpcion, Set<Eventos> eventoses, Set<Usuarios> usuarioses, Set<Intereses> intereseses) {
       this.nombre = nombre;
       this.descrpcion = descrpcion;
       this.eventoses = eventoses;
       this.usuarioses = usuarioses;
       this.intereseses = intereseses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descrpcion", length=150)
    public String getDescrpcion() {
        return this.descrpcion;
    }
    
    public void setDescrpcion(String descrpcion) {
        this.descrpcion = descrpcion;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="eventos_has_carreras", joinColumns = { 
        @JoinColumn(name="carreras_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="eventos_id", nullable=false, updatable=false) })
    public Set<Eventos> getEventoses() {
        return this.eventoses;
    }
    
    public void setEventoses(Set<Eventos> eventoses) {
        this.eventoses = eventoses;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="carreras_has_usuarios",joinColumns = { 
        @JoinColumn(name="carreras_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="usuarios_carne", nullable=false, updatable=false) })
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="carreras")
    public Set<Intereses> getIntereseses() {
        return this.intereseses;
    }
    
    public void setIntereseses(Set<Intereses> intereseses) {
        this.intereseses = intereseses;
    }




}


