package com.tservice.Model;
// Generated 14-jun-2015 22:57:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eventos generated by hbm2java
 */
@Entity
@Table(name="eventos")
public class Eventos  implements java.io.Serializable {


     private Integer id;
     private Edificio edificio;
     private Date fecha;
     private String descripcion;
     private Set<Carreras> carrerases = new HashSet(0);

    public Eventos() {
    }

	
    public Eventos(Edificio edificio) {
        this.edificio = edificio;
    }
    public Eventos(Edificio edificio, Date fecha, String descripcion, Set<Carreras> carrerases) {
       this.edificio = edificio;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.carrerases = carrerases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="lugar", nullable=false)
    public Edificio getEdificio() {
        return this.edificio;
    }
    
    public void setEdificio(Edificio edificio) {
        this.edificio = edificio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="Descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="eventos_has_carreras", catalog="coswg2", joinColumns = { 
        @JoinColumn(name="eventos_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="carreras_id", nullable=false, updatable=false) })
    public Set<Carreras> getCarrerases() {
        return this.carrerases;
    }
    
    public void setCarrerases(Set<Carreras> carrerases) {
        this.carrerases = carrerases;
    }




}


