package com.tservice.Model;
// Generated 29/06/2015 02:52:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Eventos generated by hbm2java
 */
public class Eventos  implements java.io.Serializable {


     private Integer id;
     private Edificio edificio;
     private Ubicacion ubicacion;
     private Date fecha;
     private String descripcion;
     private String titulo;
     private Set intereseses = new HashSet(0);
     private Set calificacions = new HashSet(0);
     private Set carrerases = new HashSet(0);

    public Eventos() {
    }

	
    public Eventos(Edificio edificio, String titulo) {
        this.edificio = edificio;
        this.titulo = titulo;
    }
    public Eventos(Edificio edificio, Ubicacion ubicacion, Date fecha, String descripcion, String titulo, Set intereseses, Set calificacions, Set carrerases) {
       this.edificio = edificio;
       this.ubicacion = ubicacion;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.titulo = titulo;
       this.intereseses = intereseses;
       this.calificacions = calificacions;
       this.carrerases = carrerases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Edificio getEdificio() {
        return this.edificio;
    }
    
    public void setEdificio(Edificio edificio) {
        this.edificio = edificio;
    }
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Set getIntereseses() {
        return this.intereseses;
    }
    
    public void setIntereseses(Set intereseses) {
        this.intereseses = intereseses;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }
    public Set getCarrerases() {
        return this.carrerases;
    }
    
    public void setCarrerases(Set carrerases) {
        this.carrerases = carrerases;
    }




}


