package com.tservice.Model;
// Generated 29/06/2015 02:52:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grupos generated by hbm2java
 */
public class Grupos  implements java.io.Serializable {


     private Integer id;
     private Usuarios usuarios;
     private String nombre;
     private Date fechacreacion;
     private String estado;
     private Boolean tipoprivado;
     private Set usuarioses = new HashSet(0);
     private Set mensajeses = new HashSet(0);

    public Grupos() {
    }

	
    public Grupos(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Grupos(Usuarios usuarios, String nombre, Date fechacreacion, String estado, Boolean tipoprivado, Set usuarioses, Set mensajeses) {
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.fechacreacion = fechacreacion;
       this.estado = estado;
       this.tipoprivado = tipoprivado;
       this.usuarioses = usuarioses;
       this.mensajeses = mensajeses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Boolean getTipoprivado() {
        return this.tipoprivado;
    }
    
    public void setTipoprivado(Boolean tipoprivado) {
        this.tipoprivado = tipoprivado;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set getMensajeses() {
        return this.mensajeses;
    }
    
    public void setMensajeses(Set mensajeses) {
        this.mensajeses = mensajeses;
    }




}


