package com.tservice.Model;
// Generated 14-jun-2015 22:57:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Grupos generated by hbm2java
 */
@Entity
@Table(name="grupos"
    ,catalog="coswg2"
    , uniqueConstraints = @UniqueConstraint(columnNames="identificaciongoogle") 
)
public class Grupos  implements java.io.Serializable {


     private int id;
     private Usuarios usuarios;
     private String identificaciongoogle;
     private String nombre;
     private Date fechacreacion;
     private String estado;
     private Boolean tipoprivado;
     private Set<Usuarios> usuarioses = new HashSet(0);

    public Grupos() {
    }

	
    public Grupos(int id, Usuarios usuarios, String identificaciongoogle) {
        this.id = id;
        this.usuarios = usuarios;
        this.identificaciongoogle = identificaciongoogle;
    }
    public Grupos(int id, Usuarios usuarios, String identificaciongoogle, String nombre, Date fechacreacion, String estado, Boolean tipoprivado, Set<Usuarios> usuarioses) {
       this.id = id;
       this.usuarios = usuarios;
       this.identificaciongoogle = identificaciongoogle;
       this.nombre = nombre;
       this.fechacreacion = fechacreacion;
       this.estado = estado;
       this.tipoprivado = tipoprivado;
       this.usuarioses = usuarioses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="administrador", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    
    @Column(name="identificaciongoogle", unique=true, nullable=false)
    public String getIdentificaciongoogle() {
        return this.identificaciongoogle;
    }
    
    public void setIdentificaciongoogle(String identificaciongoogle) {
        this.identificaciongoogle = identificaciongoogle;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechacreacion", length=10)
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }

    
    @Column(name="estado", length=15)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="tipoprivado")
    public Boolean getTipoprivado() {
        return this.tipoprivado;
    }
    
    public void setTipoprivado(Boolean tipoprivado) {
        this.tipoprivado = tipoprivado;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="usuarios_has_grupos", catalog="coswg2", joinColumns = { 
        @JoinColumn(name="grupos_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="usuarios_carne", nullable=false, updatable=false) })
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }

}


