package com.tservice.Model;
// Generated 29/06/2015 02:52:59 PM by Hibernate Tools 4.3.1



/**
 * Intereses generated by hbm2java
 */
public class Intereses  implements java.io.Serializable {


     private int id;
     private Carreras carreras;
     private Eventos eventos;
     private Noticias noticias;
     private String descripcion;
     private String nombre;

    public Intereses() {
    }

	
    public Intereses(int id) {
        this.id = id;
    }
    public Intereses(int id, Carreras carreras, Eventos eventos, Noticias noticias, String descripcion, String nombre) {
       this.id = id;
       this.carreras = carreras;
       this.eventos = eventos;
       this.noticias = noticias;
       this.descripcion = descripcion;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Carreras getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Carreras carreras) {
        this.carreras = carreras;
    }
    public Eventos getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Eventos eventos) {
        this.eventos = eventos;
    }
    public Noticias getNoticias() {
        return this.noticias;
    }
    
    public void setNoticias(Noticias noticias) {
        this.noticias = noticias;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


