package com.tservice.Model;
// Generated 29/06/2015 02:52:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materias generated by hbm2java
 */
public class Materias  implements java.io.Serializable {


     private int id;
     private Materias materias;
     private String nombre;
     private String memonico;
     private String grupo;
     private Set materiases = new HashSet(0);
     private Set usuarioses = new HashSet(0);

    public Materias() {
    }

	
    public Materias(int id) {
        this.id = id;
    }
    public Materias(int id, Materias materias, String nombre, String memonico, String grupo, Set materiases, Set usuarioses) {
       this.id = id;
       this.materias = materias;
       this.nombre = nombre;
       this.memonico = memonico;
       this.grupo = grupo;
       this.materiases = materiases;
       this.usuarioses = usuarioses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Materias getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Materias materias) {
        this.materias = materias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getMemonico() {
        return this.memonico;
    }
    
    public void setMemonico(String memonico) {
        this.memonico = memonico;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public Set getMateriases() {
        return this.materiases;
    }
    
    public void setMateriases(Set materiases) {
        this.materiases = materiases;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


