package com.tservice.Model;
// Generated 29/06/2015 02:52:59 PM by Hibernate Tools 4.3.1



/**
 * Mensajes generated by hbm2java
 */
public class Mensajes  implements java.io.Serializable {


     private Integer id;
     private Grupos grupos;
     private Usuarios usuariosByUsuariosorigen;
     private Usuarios usuariosByUsuariodestino;
     private String fecha;
     private String visto;
     private String contenido;

    public Mensajes() {
    }

	
    public Mensajes(Grupos grupos, Usuarios usuariosByUsuariosorigen, Usuarios usuariosByUsuariodestino) {
        this.grupos = grupos;
        this.usuariosByUsuariosorigen = usuariosByUsuariosorigen;
        this.usuariosByUsuariodestino = usuariosByUsuariodestino;
    }
    public Mensajes(Grupos grupos, Usuarios usuariosByUsuariosorigen, Usuarios usuariosByUsuariodestino, String fecha, String visto, String contenido) {
       this.grupos = grupos;
       this.usuariosByUsuariosorigen = usuariosByUsuariosorigen;
       this.usuariosByUsuariodestino = usuariosByUsuariodestino;
       this.fecha = fecha;
       this.visto = visto;
       this.contenido = contenido;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Grupos getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Grupos grupos) {
        this.grupos = grupos;
    }
    public Usuarios getUsuariosByUsuariosorigen() {
        return this.usuariosByUsuariosorigen;
    }
    
    public void setUsuariosByUsuariosorigen(Usuarios usuariosByUsuariosorigen) {
        this.usuariosByUsuariosorigen = usuariosByUsuariosorigen;
    }
    public Usuarios getUsuariosByUsuariodestino() {
        return this.usuariosByUsuariodestino;
    }
    
    public void setUsuariosByUsuariodestino(Usuarios usuariosByUsuariodestino) {
        this.usuariosByUsuariodestino = usuariosByUsuariodestino;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getVisto() {
        return this.visto;
    }
    
    public void setVisto(String visto) {
        this.visto = visto;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }




}


