package com.tservice.Model;
// Generated 30-jun-2015 13:06:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mensajes generated by hbm2java
 */
@Entity
@Table(name="mensajes")
public class Mensajes  implements java.io.Serializable {


     private Integer id;
     private Grupos grupos;
     private Usuarios usuariosByUsuariosorigen;
     private Usuarios usuariosByUsuariodestino;
     private String fecha;
     private String visto;
     private String contenido;

    public Mensajes() {
    }

    public Mensajes(Grupos grupos, Usuarios usuariosByUsuariosorigen, Usuarios usuariosByUsuariodestino, String fecha, String visto, String contenido) {
       this.grupos = grupos;
       this.usuariosByUsuariosorigen = usuariosByUsuariosorigen;
       this.usuariosByUsuariodestino = usuariosByUsuariodestino;
       this.fecha = fecha;
       this.visto = visto;
       this.contenido = contenido;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grupodestino")
    public Grupos getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Grupos grupos) {
        this.grupos = grupos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="usuariosorigen")
    public Usuarios getUsuariosByUsuariosorigen() {
        return this.usuariosByUsuariosorigen;
    }
    
    public void setUsuariosByUsuariosorigen(Usuarios usuariosByUsuariosorigen) {
        this.usuariosByUsuariosorigen = usuariosByUsuariosorigen;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="usuariodestino")
    public Usuarios getUsuariosByUsuariodestino() {
        return this.usuariosByUsuariodestino;
    }
    
    public void setUsuariosByUsuariodestino(Usuarios usuariosByUsuariodestino) {
        this.usuariosByUsuariodestino = usuariosByUsuariodestino;
    }

    
    @Column(name="fecha", length=45)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="visto", length=45)
    public String getVisto() {
        return this.visto;
    }
    
    public void setVisto(String visto) {
        this.visto = visto;
    }

    
    @Column(name="contenido")
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }




}


