package com.tservice.Model;
// Generated 29/06/2015 02:52:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Noticias generated by hbm2java
 */
public class Noticias  implements java.io.Serializable {


     private int id;
     private String contenido;
     private String autoria;
     private String titulo;
     private Set calificacions = new HashSet(0);
     private Set intereseses = new HashSet(0);

    public Noticias() {
    }

	
    public Noticias(int id) {
        this.id = id;
    }
    public Noticias(int id, String contenido, String autoria, String titulo, Set calificacions, Set intereseses) {
       this.id = id;
       this.contenido = contenido;
       this.autoria = autoria;
       this.titulo = titulo;
       this.calificacions = calificacions;
       this.intereseses = intereseses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public String getAutoria() {
        return this.autoria;
    }
    
    public void setAutoria(String autoria) {
        this.autoria = autoria;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }
    public Set getIntereseses() {
        return this.intereseses;
    }
    
    public void setIntereseses(Set intereseses) {
        this.intereseses = intereseses;
    }




}


