package com.tservice.Model;
// Generated 30-jun-2015 13:06:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Noticias generated by hbm2java
 */
@Entity
@Table(name="noticias")
public class Noticias  implements java.io.Serializable {


     private int id;
     private String contenido;
     private String autoria;
     private String titulo;
     private Set<Calificacion> calificacions = new HashSet(0);
     private Set<Intereses> intereseses = new HashSet(0);

    public Noticias() {
    }

	
    public Noticias(int id) {
        this.id = id;
    }
    public Noticias(int id, String contenido, String autoria, String titulo, Set<Calificacion> calificacions, Set<Intereses> intereseses) {
       this.id = id;
       this.contenido = contenido;
       this.autoria = autoria;
       this.titulo = titulo;
       this.calificacions = calificacions;
       this.intereseses = intereseses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="contenido", length=1000)
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    
    @Column(name="autoria", length=45)
    public String getAutoria() {
        return this.autoria;
    }
    
    public void setAutoria(String autoria) {
        this.autoria = autoria;
    }

    
    @Column(name="titulo", length=100)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="noticias")
    public Set<Calificacion> getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set<Calificacion> calificacions) {
        this.calificacions = calificacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="noticias")
    public Set<Intereses> getIntereseses() {
        return this.intereseses;
    }
    
    public void setIntereseses(Set<Intereses> intereseses) {
        this.intereseses = intereseses;
    }




}


