package com.tservice.Model;
// Generated 29/06/2015 02:52:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubicacion generated by hbm2java
 */
public class Ubicacion  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private String posicion;
     private Set eventoses = new HashSet(0);

    public Ubicacion() {
    }

    public Ubicacion(String nombre, String descripcion, String posicion, Set eventoses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.posicion = posicion;
       this.eventoses = eventoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getPosicion() {
        return this.posicion;
    }
    
    public void setPosicion(String posicion) {
        this.posicion = posicion;
    }
    public Set getEventoses() {
        return this.eventoses;
    }
    
    public void setEventoses(Set eventoses) {
        this.eventoses = eventoses;
    }




}


