package com.tservice.Model;
// Generated 29/06/2015 02:52:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String carne;
     private String nombre;
     private String identificaciongoogle;
     private String email;
     private String contrasena;
     private String perfil;
     private String identificacion;
     private Integer semestre;
     private Set carrerases = new HashSet(0);
     private Set gruposes = new HashSet(0);
     private Set calificacions = new HashSet(0);
     private Set mensajesesForUsuariosorigen = new HashSet(0);
     private Set materiases = new HashSet(0);
     private Set mensajesesForUsuariodestino = new HashSet(0);
     private Set gruposes_1 = new HashSet(0);

    public Usuarios() {
    }
    
    
    
    public Usuarios(String carne) {
        this.carne = carne;
      
    }
    
    public Usuarios(String carne, String identificacion) {
        this.carne = carne;
        this.identificacion = identificacion;
    }
    public Usuarios(String carne, String nombre, String identificaciongoogle, String email, String contrasena, String perfil, String identificacion, Integer semestre, Set carrerases, Set gruposes, Set calificacions, Set mensajesesForUsuariosorigen, Set materiases, Set mensajesesForUsuariodestino, Set gruposes_1) {
       this.carne = carne;
       this.nombre = nombre;
       this.identificaciongoogle = identificaciongoogle;
       this.email = email;
       this.contrasena = contrasena;
       this.perfil = perfil;
       this.identificacion = identificacion;
       this.semestre = semestre;
       this.carrerases = carrerases;
       this.gruposes = gruposes;
       this.calificacions = calificacions;
       this.mensajesesForUsuariosorigen = mensajesesForUsuariosorigen;
       this.materiases = materiases;
       this.mensajesesForUsuariodestino = mensajesesForUsuariodestino;
       this.gruposes_1 = gruposes_1;
    }
   
    public String getCarne() {
        return this.carne;
    }
    
    public void setCarne(String carne) {
        this.carne = carne;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getIdentificaciongoogle() {
        return this.identificaciongoogle;
    }
    
    public void setIdentificaciongoogle(String identificaciongoogle) {
        this.identificaciongoogle = identificaciongoogle;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public Integer getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Integer semestre) {
        this.semestre = semestre;
    }
    public Set getCarrerases() {
        return this.carrerases;
    }
    
    public void setCarrerases(Set carrerases) {
        this.carrerases = carrerases;
    }
    public Set getGruposes() {
        return this.gruposes;
    }
    
    public void setGruposes(Set gruposes) {
        this.gruposes = gruposes;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }
    public Set getMensajesesForUsuariosorigen() {
        return this.mensajesesForUsuariosorigen;
    }
    
    public void setMensajesesForUsuariosorigen(Set mensajesesForUsuariosorigen) {
        this.mensajesesForUsuariosorigen = mensajesesForUsuariosorigen;
    }
    public Set getMateriases() {
        return this.materiases;
    }
    
    public void setMateriases(Set materiases) {
        this.materiases = materiases;
    }
    public Set getMensajesesForUsuariodestino() {
        return this.mensajesesForUsuariodestino;
    }
    
    public void setMensajesesForUsuariodestino(Set mensajesesForUsuariodestino) {
        this.mensajesesForUsuariodestino = mensajesesForUsuariodestino;
    }
    public Set getGruposes_1() {
        return this.gruposes_1;
    }
    
    public void setGruposes_1(Set gruposes_1) {
        this.gruposes_1 = gruposes_1;
    }




}


